import type { JobDef } from "./types.js";

// §6 full job table. baseWage = dollars/hour pre-economy.
export const jobs: JobDef[] = [
  { id: "zMart.clerk", locationId: "zMart", title: "Clerk", baseWage: 5, reqExperience: 10, reqDependibility: 10, reqDegrees: [], uniform: "casual" },
  { id: "zMart.assistantManager", locationId: "zMart", title: "Assistant Manager", baseWage: 7, reqExperience: 20, reqDependibility: 20, reqDegrees: [], uniform: "dress" },
  { id: "zMart.manager", locationId: "zMart", title: "Manager", baseWage: 8, reqExperience: 30, reqDependibility: 30, reqDegrees: ["juniorCollege"], uniform: "business" },
  { id: "monolithBurgers.cook", locationId: "monolithBurgers", title: "Cook", baseWage: 5, reqExperience: 0, reqDependibility: 10, reqDegrees: [], uniform: "casual", alwaysApproved: true },
  { id: "monolithBurgers.clerk", locationId: "monolithBurgers", title: "Clerk", baseWage: 6, reqExperience: 10, reqDependibility: 20, reqDegrees: [], uniform: "casual" },
  { id: "monolithBurgers.assistantManager", locationId: "monolithBurgers", title: "Assistant Manager", baseWage: 7, reqExperience: 20, reqDependibility: 30, reqDegrees: [], uniform: "casual" },
  { id: "monolithBurgers.manager", locationId: "monolithBurgers", title: "Manager", baseWage: 8, reqExperience: 30, reqDependibility: 40, reqDegrees: ["juniorCollege"], uniform: "dress" },
  { id: "qtClothing.janitor", locationId: "qtClothing", title: "Janitor", baseWage: 6, reqExperience: 10, reqDependibility: 20, reqDegrees: [], uniform: "casual" },
  { id: "qtClothing.salesperson", locationId: "qtClothing", title: "Salesperson", baseWage: 8, reqExperience: 30, reqDependibility: 30, reqDegrees: [], uniform: "dress" },
  { id: "qtClothing.assistantManager", locationId: "qtClothing", title: "Assistant Manager", baseWage: 9, reqExperience: 40, reqDependibility: 40, reqDegrees: ["juniorCollege"], uniform: "business" },
  { id: "qtClothing.manager", locationId: "qtClothing", title: "Manager", baseWage: 12, reqExperience: 50, reqDependibility: 50, reqDegrees: ["businessAdmin"], uniform: "business" },
  { id: "socketCity.clerk", locationId: "socketCity", title: "Clerk", baseWage: 6, reqExperience: 10, reqDependibility: 20, reqDegrees: [], uniform: "casual" },
  { id: "socketCity.salesperson", locationId: "socketCity", title: "Salesperson", baseWage: 7, reqExperience: 30, reqDependibility: 30, reqDegrees: [], uniform: "dress" },
  { id: "socketCity.electronicsRepairman", locationId: "socketCity", title: "Electronics Repairman", baseWage: 11, reqExperience: 40, reqDependibility: 40, reqDegrees: ["electronics"], uniform: "casual" },
  { id: "socketCity.manager", locationId: "socketCity", title: "Manager", baseWage: 14, reqExperience: 40, reqDependibility: 40, reqDegrees: ["electronics", "juniorCollege"], uniform: "business" },
  { id: "hiTechU.janitor", locationId: "hiTechU", title: "Janitor", baseWage: 5, reqExperience: 10, reqDependibility: 10, reqDegrees: [], uniform: "casual" },
  { id: "hiTechU.teacher", locationId: "hiTechU", title: "Teacher", baseWage: 11, reqExperience: 40, reqDependibility: 50, reqDegrees: ["academic"], uniform: "dress" },
  { id: "hiTechU.professor", locationId: "hiTechU", title: "Professor", baseWage: 20, reqExperience: 50, reqDependibility: 60, reqDegrees: ["research"], uniform: "dress" },
  { id: "factory.janitor", locationId: "factory", title: "Janitor", baseWage: 7, reqExperience: 10, reqDependibility: 20, reqDegrees: [], uniform: "casual" },
  { id: "factory.assemblyWorker", locationId: "factory", title: "Assembly Worker", baseWage: 8, reqExperience: 30, reqDependibility: 30, reqDegrees: ["tradeSchool"], uniform: "casual" },
  { id: "factory.secretary", locationId: "factory", title: "Secretary", baseWage: 9, reqExperience: 40, reqDependibility: 40, reqDegrees: ["juniorCollege"], uniform: "dress" },
  { id: "factory.machinistsHelper", locationId: "factory", title: "Machinist's Helper", baseWage: 10, reqExperience: 40, reqDependibility: 40, reqDegrees: ["preEngineering"], uniform: "casual" },
  { id: "factory.executiveSecretary", locationId: "factory", title: "Executive Secretary", baseWage: 18, reqExperience: 50, reqDependibility: 50, reqDegrees: ["businessAdmin"], uniform: "business" },
  { id: "factory.machinist", locationId: "factory", title: "Machinist", baseWage: 19, reqExperience: 50, reqDependibility: 50, reqDegrees: ["engineering"], uniform: "casual" },
  { id: "factory.departmentManager", locationId: "factory", title: "Department Manager", baseWage: 22, reqExperience: 60, reqDependibility: 60, reqDegrees: ["juniorCollege", "engineering"], uniform: "business" },
  { id: "factory.engineer", locationId: "factory", title: "Engineer", baseWage: 23, reqExperience: 60, reqDependibility: 60, reqDegrees: ["juniorCollege", "engineering"], uniform: "business" },
  { id: "factory.generalManager", locationId: "factory", title: "General Manager", baseWage: 25, reqExperience: 70, reqDependibility: 70, reqDegrees: ["businessAdmin", "engineering"], uniform: "business" },
  { id: "bank.janitor", locationId: "bank", title: "Janitor", baseWage: 6, reqExperience: 10, reqDependibility: 20, reqDegrees: [], uniform: "casual" },
  { id: "bank.teller", locationId: "bank", title: "Teller", baseWage: 10, reqExperience: 40, reqDependibility: 40, reqDegrees: ["juniorCollege"], uniform: "dress" },
  { id: "bank.assistantManager", locationId: "bank", title: "Assistant Manager", baseWage: 14, reqExperience: 50, reqDependibility: 50, reqDegrees: ["businessAdmin"], uniform: "business" },
  { id: "bank.manager", locationId: "bank", title: "Manager", baseWage: 19, reqExperience: 60, reqDependibility: 60, reqDegrees: ["businessAdmin"], uniform: "business" },
  { id: "bank.broker", locationId: "bank", title: "Broker", baseWage: 22, reqExperience: 70, reqDependibility: 70, reqDegrees: ["businessAdmin", "academic"], uniform: "business" },
  { id: "blacksMarket.janitor", locationId: "blacksMarket", title: "Janitor", baseWage: 6, reqExperience: 10, reqDependibility: 10, reqDegrees: [], uniform: "casual" },
  { id: "blacksMarket.checker", locationId: "blacksMarket", title: "Checker", baseWage: 8, reqExperience: 20, reqDependibility: 20, reqDegrees: [], uniform: "casual" },
  { id: "blacksMarket.butcher", locationId: "blacksMarket", title: "Butcher", baseWage: 12, reqExperience: 30, reqDependibility: 30, reqDegrees: ["tradeSchool"], uniform: "casual" },
  { id: "blacksMarket.assistantManager", locationId: "blacksMarket", title: "Assistant Manager", baseWage: 15, reqExperience: 40, reqDependibility: 40, reqDegrees: ["juniorCollege"], uniform: "dress" },
  { id: "blacksMarket.manager", locationId: "blacksMarket", title: "Manager", baseWage: 18, reqExperience: 50, reqDependibility: 50, reqDegrees: ["businessAdmin"], uniform: "business" },
  { id: "rentOffice.groundskeeper", locationId: "rentOffice", title: "Groundskeeper", baseWage: 7, reqExperience: 10, reqDependibility: 20, reqDegrees: [], uniform: "casual" },
  { id: "rentOffice.apartmentManager", locationId: "rentOffice", title: "Apartment Manager", baseWage: 9, reqExperience: 30, reqDependibility: 30, reqDegrees: ["juniorCollege"], uniform: "casual" },
];
